#!/bin/bash -e
if [[ ! -f "/home/spark-bdfa7f15-7d48-42de-9eb9-d0/tmp/uv/uv_0.6.10_linux_amd64" ]]; then
  curl -LsSf https://astral.sh/uv/0.6.10/install.sh | sh
  exec "$HOME/.local/bin/uv" "$@"
fi
exec "/home/spark-bdfa7f15-7d48-42de-9eb9-d0/tmp/uv/uv_0.6.10_linux_amd64" "$@"
