#!/bin/bash -e
if [[ ! -f "/home/spark-e6efc248-df9f-45e9-85f8-34/tmp/uv/uv_0.6.10_linux_amd64" ]]; then
  curl -LsSf https://astral.sh/uv/0.6.10/install.sh | sh
  exec "$HOME/.local/bin/uv" "$@"
fi
exec "/home/spark-e6efc248-df9f-45e9-85f8-34/tmp/uv/uv_0.6.10_linux_amd64" "$@"
