#!/bin/bash -e
if [[ ! -f "/home/spark-894c4c5c-4ecb-4062-80fd-88/tmp/uv/uv_0.6.10_linux_amd64" ]]; then
  curl -LsSf https://astral.sh/uv/0.6.10/install.sh | sh
  exec "$HOME/.local/bin/uv" "$@"
fi
exec "/home/spark-894c4c5c-4ecb-4062-80fd-88/tmp/uv/uv_0.6.10_linux_amd64" "$@"
