#!/bin/bash -e
if [[ ! -f "/home/spark-cf5deb74-df5a-467f-aa3c-f3/tmp/uv/uv_0.6.10_linux_amd64" ]]; then
  curl -LsSf https://astral.sh/uv/0.6.10/install.sh | sh
  exec "$HOME/.local/bin/uv" "$@"
fi
exec "/home/spark-cf5deb74-df5a-467f-aa3c-f3/tmp/uv/uv_0.6.10_linux_amd64" "$@"
